import { randomUUID, type UUID } from "crypto";
import mongoose, { Document } from "mongoose";

export interface IPatient extends Document {
  _id: UUID;
  user_id: string;
  patient_code: string;
  emergency_contact: {
    name?: string;
    phone?: string;
  };
  last_visit_date?: Date;
  last_test_type?: string;
  is_active?: boolean;
  created_at: Date;
  updated_at: Date;
  created_by?: string;
  is_deleted?: boolean;
  deleted_at?: Date;
}

const patientSchema = new mongoose.Schema<IPatient>(
  {
    _id: {
      type: String,
      default: () => randomUUID(),
    },
    user_id: {
      type: String,
      required: [true, "User ID is required!"],
      ref: "User", // Reference to IAM Service User collection
    },
    patient_code: {
      type: String,
      // Will be auto-generated by pre-save hook
      trim: true,
      // unique: true - Removed to avoid duplicate with schema.index() below
    },
    emergency_contact: {
      type: {
        name: {
          type: String,
          trim: true,
        },
        phone: {
          type: String,
          trim: true,
        },
      },
      required: [true, "Emergency contact is required!"],
      _id: false, // Disable _id for subdocument
    },
    last_visit_date: {
      type: Date,
    },
    last_test_type: {
      type: String,
      trim: true,
      maxlength: [50, "Test type cannot exceed 50 characters!"],
    },
    is_active: {
      type: Boolean,
      default: true,
    },
    created_by: {
      type: String,
      ref: "User", // Reference to IAM Service User collection
    },
    is_deleted: {
      type: Boolean,
      default: false,
    },
    deleted_at: {
      type: Date,
    },
  },
  {
    _id: false,
    timestamps: { createdAt: 'created_at', updatedAt: 'updated_at' },
    collection: "Patient",
  }
);

// Indexes - Based on ERD
patientSchema.index({ patient_code: 1 }, { unique: true });
patientSchema.index({ user_id: 1 });
patientSchema.index({ last_visit_date: 1 });
patientSchema.index({ is_active: 1 });
patientSchema.index({ is_deleted: 1, last_visit_date: 1 }); // Optimized for active patients sorted by visit
patientSchema.index({ is_deleted: 1, user_id: 1 }); // Optimized for active patients by user

// Pre-save hook to generate UUID and patient code
patientSchema.pre("save", async function (next) {
  if (!this._id) {
    this._id = randomUUID();
  }
  
  // Auto-generate patient code if not provided: PT202510240001
  if (!this.patient_code) {
    const date = new Date();
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, "0");
    const day = String(date.getDate()).padStart(2, "0");
    
    // Count existing patients for this date
    const count = await mongoose.model("Patient").countDocuments({
      patient_code: new RegExp(`^PT${year}${month}${day}`),
    });
    
    const sequence = String(count + 1).padStart(4, "0");
    this.patient_code = `PT${year}${month}${day}${sequence}`;
  }
  
  next();
});

const Patient = mongoose.model<IPatient>("Patient", patientSchema);

export default Patient;
